Repository mina-gwak/issue-tracker, pull requests merged in 2022-08, with the labels that each got.

#64 [FE] 마일스톤 & 라벨 페이지 스타일 코드 분리
  FE/src/components/InputForm/InputForm.style.ts
  FE/src/components/InputForm/index.tsx
  FE/src/components/InputRadio/index.tsx
  FE/src/components/LabelCreateEditForm/LabelCreateEdit.tsx
  FE/src/components/LabelCreateEditForm/LabelCreateEditForm.style.ts
  FE/src/components/LabelCreateEditForm/index.tsx
  FE/src/components/LabelTable/LabelBadge.tsx
  FE/src/components/LabelTable/LabelItem.tsx
  FE/src/components/LabelTable/LabelTable.style.ts
  FE/src/components/LabelTable/LabelTableHeader.tsx
  FE/src/components/LabelTable/index.tsx
  FE/src/components/MilestoneCreateEditForm/MilestoneCreateEditForm.style.ts
  FE/src/components/MilestoneCreateEditForm/index.tsx
  FE/src/components/MilestoneTable/MilestoneInfo.tsx
  FE/src/components/MilestoneTable/MilestoneTable.style.ts
  FE/src/components/MilestoneTable/MilestoneTableHeader.tsx
  FE/src/components/MilestoneTable/index.tsx
  FE/src/components/TabsPageHeader/TabsPageHeader.style.ts
  FE/src/components/TabsPageHeader/index.tsx
  FE/src/pages/Label/Label.style.ts
  FE/src/pages/Label/index.tsx
  FE/src/pages/Milestone/Milestone.style.ts
  FE/src/pages/Milestone/index.tsx
Labels: 🖥 FE, 💊 Refactor, 👑 Khan

#71 [BE] debug : issue List 조회 에러 해결
  BE/src/main/java/com/codesquad/issueTracker/common/infrastructure/aspect/LogAspect.java
  BE/src/main/java/com/codesquad/issueTracker/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issueTracker/issue/application/IssueService.java
  BE/src/main/java/com/codesquad/issueTracker/issue/application/dto/IssueCoverResponse.java
  BE/src/main/java/com/codesquad/issueTracker/issue/application/dto/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/Issue.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/repository/IssueRepositoryCustom.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/repository/IssueRepositoryCustomImpl.java
  BE/src/test/java/com/codesquad/issueTracker/unit/issue/application/IssueServiceTest.java
Labels: ⚙️ BE, 🔧 Fix, 🚘 Lucid

#72 [FE] 디테일 페이지 구현
  FE/package-lock.json
  FE/package.json
  FE/src/assets/icons/closeIssue.svg
  FE/src/assets/icons/emoji.svg
  FE/src/assets/icons/index.tsx
  FE/src/assets/icons/issueDelete.svg
  FE/src/assets/icons/openIssue.svg
  FE/src/components/CommentList/Comment.tsx
  FE/src/components/CommentList/CommentList.style.ts
  FE/src/components/CommentList/EditComment.tsx
  FE/src/components/CommentList/index.tsx
  FE/src/components/DetailIssueHeader/DetailIssueHeader.style.ts
  FE/src/components/DetailIssueHeader/DetailIssueStatus.tsx
  FE/src/components/DetailIssueHeader/HeaderEditMode.tsx
  FE/src/components/DetailIssueHeader/HeaderViewMode.tsx
  FE/src/components/DetailIssueHeader/index.tsx
  FE/src/components/IssueTable/Issue/Issue.style.ts
  FE/src/components/IssueTable/Issue/index.tsx
  FE/src/components/common/Icon/constants.ts
  FE/src/components/common/Textarea/Textarea.stories.tsx
  FE/src/components/common/Textarea/Textarea.style.ts
  FE/src/components/common/Textarea/index.tsx
  FE/src/constants/api.ts
  FE/src/pages/AddIssue/index.tsx
  FE/src/pages/IssueDetail/IssueDetail.style.ts
  FE/src/pages/IssueDetail/index.tsx
  FE/src/router/index.tsx
  FE/src/store/detailIssue.ts
  FE/src/type/detailIssueType.ts
  FE/src/utils/api/fetchComment.ts
  FE/src/utils/api/fetchDetailIssue.ts
Labels: 🖥 FE, 💡 Feature, 👑 Khan

#75 [BE] 요청사항 적용
  BE/src/main/java/com/codesquad/issueTracker/comment/domain/Comment.java
  BE/src/main/java/com/codesquad/issueTracker/comment/domain/CommentStatus.java
  BE/src/main/java/com/codesquad/issueTracker/issue/application/IssueService.java
  BE/src/main/java/com/codesquad/issueTracker/issue/application/dto/CommentOutline.java
  BE/src/main/java/com/codesquad/issueTracker/issue/application/dto/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/Image.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/Issue.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/repository/IssueRepository.java
  BE/src/main/java/com/codesquad/issueTracker/issue/domain/repository/IssueRepositoryCustomImpl.java
  BE/src/main/java/com/codesquad/issueTracker/issue/presentation/IssueController.java
  BE/src/main/java/com/codesquad/issueTracker/issue/presentation/dto/IssueContentsRequest.java
  BE/src/main/java/com/codesquad/issueTracker/label/domain/LabelRepository.java
  BE/src/main/java/com/codesquad/issueTracker/milestone/application/dto/MilestoneSingleInfoResponse.java
  BE/src/main/java/com/codesquad/issueTracker/user/domain/repository/UserRepository.java
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/com/codesquad/issueTracker/unit/issue/application/IssueServiceTest.java
  BE/src/test/java/com/codesquad/issueTracker/unit/issue/domain/CommentTest.java
  BE/src/test/java/com/codesquad/issueTracker/unit/issue/domain/IssueRepositoryTest.java
  BE/src/test/java/com/codesquad/issueTracker/unit/issue/presentation/IssueControllerTest.java
  BE/src/test/java/com/codesquad/issueTracker/unit/milestone/presentation/MilestoneControllerTest.java
  BE/src/test/java/com/codesquad/issueTracker/unit/user/domain/UserRepositoryTest.java
Labels: ⚙️ BE, 💡 Feature, 🔧 Fix, 💊 Refactor, 🚘 Lucid

#78 [FE] 마일스톤 요청 에러 해결
  FE/src/components/CommentList/Comment.tsx
  FE/src/components/CommentList/CommentList.style.ts
  FE/src/components/CommentList/EditComment.tsx
  FE/src/components/CommentList/index.tsx
  FE/src/components/DetailIssueHeader/HeaderViewMode.tsx
  FE/src/components/DetailIssueHeader/index.tsx
  FE/src/components/InputRadio/index.tsx
  FE/src/components/LabelCreateEditForm/LabelCreateEdit.tsx
  FE/src/components/LabelCreateEditForm/index.tsx
  FE/src/components/MilestoneCreateEditForm/index.tsx
  FE/src/components/MilestoneTable/MilestoneInfo.tsx
  FE/src/components/MilestoneTable/MilestoneItem.tsx
  FE/src/components/MilestoneTable/MilestoneTable.style.ts
  FE/src/components/MilestoneTable/index.tsx
  FE/src/hooks/useInput.ts
  FE/src/pages/IssueDetail/index.tsx
  FE/src/store/milestone.ts
  FE/src/type/detailIssueType.ts
  FE/src/utils/api/fetchMilestone.ts
  FE/src/utils/date.ts
Labels: 🖥 FE, 💡 Feature, 🔧 Fix, 💊 Refactor, 👑 Khan
